### PR TITLE
created website in react

### PR DESCRIPTION
**Pull request by janmesh799**
i have made this webiste in react

### CODE REVIEW

**Comment by naman-ng** [comment]
Nice work but I asked to make it exactly the same. The navbar and footer are way different, also the body's font is different. Please improvise.

**Comment by janmesh799** [comment]
ohk ✌

**Comment by janmesh799** [comment]
i have made changes 
you can check

**Comment by naman-ng** [comment]
Add the dropdown effect to the 'sponsors' and 'events' buttons on the navbar. Also, add the '404' page link to its dropdown buttons.

**Comment by janmesh799** [comment]
they already have dropdown effect to the 'sponsors' and 'events' buttons

**Comment by janmesh799** [comment]
can you merge this much 
and you should now divide this website into smaller parts 
so , contributing to this project became easy 
like one issue for navbar, anther for main banner, another for footer, etc

**Pull request merged**
